# ZMK build configuration
---
include:
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_RGB_UNDERGLOW=y -DCONFIG_ZMK_BLE=y
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_RGB_UNDERGLOW=y -DCONFIG_ZMK_BLE=y
    artifact-name: corne_right
